### ISSUE TITLE
angularjs variable (product id) pass to javascript function

### ISSUE THREAD

**Issue by cyrusonline** [poiuytrez/AndroidInAppBilling#110]
i am using angularjs to build an app, however, i cannot figure out how to pass {{product_id}} to the javascript function of this plugin. 

So, i hope instead of purchasing gas
 function buy(){
                // make the purchase
                inappbilling.buy(successHandler, errorHandler,"gas");

            }

we can pass the variable {{product_id}} into the above function
 function buy(item){
                // make the purchase
                inappbilling.buy(successHandler, errorHandler,item);

            }

Thanks

**Comment by driannaude** [comment]
Hey @cyrusonline, I think i understand your request, you want the product ID to be dynamic, rather than a hardcoded string? in that case you can probably pass it down the scope method that's attached to your view user action, i.e.:

``` html
<!-- ng-repeat example -->
<button ng-click="buyThisItem(item.productID)" ng-repeat="item in storeItems">Buy Now</button>
<!-- Just as a string example -->
<button ng-click="buyThisItem('product.id.here')">Buy Now</button>
```

``` javascript
// in your controller
$scope.buyThisItem = function(productId){
  inappbilling.buy(successHandler, errorHandler,productId);
}
```

I would recommend you generate your list of available products from inappbilling.getAvailableProducts() [[see here](https://github.com/poiuytrez/AndroidInAppBilling/#get-available-products)] and also cross compare with your owned products if they are non-consumable using inappbilling.refreshPurchases() [[see here](https://github.com/poiuytrez/AndroidInAppBilling/#force-refresh-owned-products)].

It will help avoid so many errors that pertain to state with the products/store.

**Comment by cyrusonline** [comment]
Thank you @driannaude for your reply, do you also know 
1. how to customize the successhandler, i tried to create successhandler2 function, but at last the app still use successhandler function. (As i want to have different feedback . one is when customer click buy button , second is when the page checked the customer did not purchase that item, it will not show the purchased item(e.g. picture or mp3 link)


            function successHandler (result) {
                var strResult = "";
                if(typeof result === 'object') {
                    strResult = JSON.stringify(result);
                } else {
                    strResult = result;
                }
                alert("SUCCESS: \r\n"+strResult );
            }

function successHandler2 () {
                $( "#my" ).append("<strong>success</strong>");
            }
function getPurchase_infinite(){
                inappbilling.getPurchases(successHandler2, errorHandler2, "infinite_gas");
            }


2. actually how to let the page check whether the item("infinte_gas") get purchased, the above function seem also not work

Thanks~~~

**Comment by driannaude** [comment]
So you would like to know whether the purchase was successful? Or whether an item is already owned?

**Comment by cyrusonline** [comment]
The later one. I want to make there is a list page, after clicking a specific item, then go to another page, in this page if the item is already purchased , hide the buy button and show the item(e.g. download link). otherwise, if  not purchased, show the buy button only

**Comment by driannaude** [comment]
You can use the refreshPurchases() method to force retrieving a list of owned products from the app store. From the documentation:

_The plugin retrieve the list of owned products from Google Play during the initialisation and cache the it internally, the getPurchase method returns the local copy of this list.
If for some reason you have to force refresh the list of the owned products, use the refreshPurchases method._
``` javascript
inappbilling.refreshPurchases(success, fail);
```
_The parameters are exactly the same, the success callback provides also an array with the owned products._

On success you will be returned an array of owned products. Compare this against your products in your view and apply the appropriate logic to show/change state. :smile_cat:

**Comment by driannaude** [comment]
Also, as per request on some of your other threads, please close this topic if your initial question was answered, we can continue this discussion at #109, which relates to your second question in this thread

**Comment by cyrusonline** [comment]
thanks,  I understand your algorithm, but as I am an newbie, could you please teach me how to check whether the product is bought by comparing with the return json object of "refreshPurchase". I found a lot in stackflow, but they usually talk about hasownproperty but not the value. For example I want to check whether product id="apple" purchased.

**Comment by cyrusonline** [comment]
close
