### ISSUE TITLE
Problems with v3

### ISSUE THREAD

**Issue by ewpdesign** [poiuytrez/AndroidInAppBilling#32]
First, thank you so much for the work you have done in developing this plugin!  

It seems like the new v3 release does not match the documentation.  I opened up the inappbilling.js file and removed the "prototype." and at least got the init function to fire.  Also, the case has changed in the new .js file and my program had to be changed accordingly  (the sample documentation is still all lower case).  

Aside from the alert I placed in the .js file firing. I am not getting any success or error responses from the function.  I have checked the setup a million times and cannot see anything that I could have missed.

I'm so close.....

**Comment by Godlike-** [comment]
Alright, for I'm far too often in this mess. But oh well, I managed to correct the situation (with most likely deprecated code), here's a fix, for it is still working for me.

2 things needs to be done:
 - use the .JS, and put a wrapper around (as shown below):
 - rem the module.exports thingie. it will be of no need in the future.

It will look like this...

(function(cordova) {
        <b>... rest of JS file...</b>
       <b>//module.exports = new InAppBilling();</b>
	cordova.addConstructor(function() {
		if(!window.plugins) window.plugins = {};
		window.plugins.inappbilling = new InAppBilling();
	});
})(window.cordova || window.Cordova);

so now, from where you normally initialize the plugin, you just need to declare as follow:
var inappbilling = window.plugins.inappbilling;
inappbilling.init(successHandler, errorHandler, {showLog:false});

From there given your plugin was correctly referenced in your project it will work.

**Comment by poiuytrez** [comment]
Feel free to make a pull request.

**Comment by equry** [comment]
Hi,
is it possible to use this pluggin with phonegap remote build, if yes please share the steps how?

if no, please share how to add this to an existing remote phone gap project.

here is my project,

1) i have a single html file like following and config file has this setting

<gap:plugin name="com.smartmobilesoftware.inappbilling" version="3.0.2" />

2)
here is the index file i am using

<!DOCTYPE html>
<html>
<head>
</head>
<body>

<button onclick="init()">Click me</button>
        <h1>Hello World</h1>
        <button onclick="init()">Initalize the billing plugin</button>
        <button onclick="buy()">Purchase</button>
        <button onclick="ownedProducts()">Owned products</button>
        <button onclick="consumePurchase()">Consume purchase</button>
        <button onclick="subscribe()">Subscribe</button>
        <button onclick="getDetails()">Query Details</button>
        <button onclick="getAvailable()">Get Available Products</button>
<p id="demo"></p>

<p>A function is triggered when the button is clicked. The function outputs some text in a p element with id="demo".</p>

<script>
	function myFunction() {
		document.getElementById("demo").innerHTML = "Hello World";
	}
	alert('1');
	var inappbilling = window.plugins.inappbilling;
	alert('2');
	function successHandler (result) {
		alert('successhandler');
		var strResult = "";
		if(typeof result === 'object') {
			strResult = JSON.stringify(result);
		} else {
			strResult = result;
		}
		alert("SUCCESS: \r\n"+strResult );
	}

	function errorHandler (error) {
		alert("ERROR: \r\n"+error );
	}

	// Click on init button
	function init(){
		// Initialize the billing plugin
		//myOwnKeyRSABase64App FROM GOOGLE DEVELOPERS CONSOLE
		alert('init');
		inappbilling.init(successHandler, errorHandler, {showLog:true, key: 'mykey'});
		alert('after init');
	}

	// Click on purchase button
	function buy(){
		// make the purchase
		alert('buy');
		inappbilling.buy(successHandler, errorHandler,"gas");

	}

	// Click on ownedProducts button
	function ownedProducts(){
		// Initialize the billing plugin
		alert('ownedProducts');
		inappbilling.getPurchases(successHandler, errorHandler);

	}

	// Click on Consume purchase button
	function consumePurchase(){
		alert('consumePurchase');
		inappbilling.consumePurchase(successHandler, errorHandler, "gas");
	}

	// Click on subscribe button
	function subscribe(){
		// make the purchase
		alert('subscribe');
		inappbilling.subscribe(successHandler, errorHandler,"infinite_gas");

	}

	// Click on Query Details button
	function getDetails(){
		// Query the store for the product details
		alert('getDetails');
		inappbilling.getProductDetails(successHandler, errorHandler, ["gas","infinite_gas"]);

	}

	// Click on Get Available Products button
	function getAvailable(){
		// Get the products available for purchase.
		alert('available products');
		inappbilling.getAvailableProducts(successHandler, errorHandler);
		alert('available products');
	}
</script>

</body>
</html>

**Comment by beulahkiruba** [comment]
add the content of the "inappbilling.js" like:

// this is "inappbilling.js file"
cordova.define("com.smartmobilesoftware.inappbilling.InAppBilling", function(require, exports, module)
{
//content of the "inappbilling.js" goes here
});

// all the best!
